"""
Django settings for django_site project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%axio27-p=06@^w9x-7_r=zqf4xal-xv@_0e3bvl&oftpip*5$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'courses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/templates',
        ], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# python-social-auth
AUTHENTICATION_BACKENDS = (
    'auth_backends.backends.EdXOAuth2',
)
SOCIAL_AUTH_POSTGRES_JSONFIELD = True

# edx-auth-backends
SOCIAL_AUTH_EDX_OAUTH2_KEY = 'CwzF9gmuo6Aya4S3e2P8YJJuEQKcqHQyl1MQVPLS'
SOCIAL_AUTH_EDX_OAUTH2_SECRET = 'qOtf5dq17ImlDGcn6sLVVSFWTiOqJffG2X177LBOarUcL1n8lKs4IA9B6AWevwZWLDHeq0ckZvgo6wyyjyeR9BB6pvCsaPXd0GIyyvRLmDkdlmRVDrcP2gJZLSxrcwzc'
SOCIAL_AUTH_EDX_OAUTH2_AUTHORIZATION_URL = 'https://panthro.sandbox.edx.org/oauth2/authorize'
SOCIAL_AUTH_EDX_OAUTH2_ACCESS_TOKEN_URL = 'https://panthro.sandbox.edx.org/oauth2/access_token'
SOCIAL_AUTH_EDX_OAUTH2_LOGOUT_URL = 'https://panthro.sandbox.edx.org/logout'
SOCIAL_AUTH_EDX_OAUTH2_LOGIN_REDIRECT_URL = 'http://localhost:8000/courses'

SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
SOCIAL_AUTH_STRATEGY = 'auth_backends.strategies.EdxDjangoStrategy'
JWS_HMAC_SIGNING_KEY = 'SET-ME-PLEASE'
